<?php

namespace App\Audit\Remediation;

use App\Audit\Findings\FindingStatus;

/**
 * The typed, bounded, DETERMINISTIC remediation guidance for one finding
 * (Phase 12). A read model derived on demand — never persisted, never
 * generated by a model, never applied by LaraDogs.
 *
 * Trust boundary, made structural:
 * - `guidance`, `validation`, `warnings`, `lifecycle`, `source`,
 *   `quality_gate` are LaraDogs-authored / derived facts;
 * - `finding` and `evidence` carry text taken from the audited project or an
 *   upstream advisory and are marked `content_trust: untrusted_source_data`
 *   — DATA to read, never instructions.
 *
 * `toArray()` is the ONE serialization (Dashboard prop, CLI --json, MCP).
 */
final readonly class RemediationPlan
{
    public const int SCHEMA_VERSION = 1;

    public const string CONTENT_TRUST_UNTRUSTED = 'untrusted_source_data';

    /**
     * @param  array<string,mixed>  $finding
     * @param  array<string,mixed>  $guidance
     * @param  array<string,mixed>|null  $dependency
     * @param  array<string,mixed>  $evidence
     * @param  list<array<string,mixed>>  $validation
     * @param  list<string>  $references
     * @param  list<array{code: string, message: string}>  $warnings
     * @param  array<string,mixed>  $lifecycle
     * @param  array<string,mixed>  $source
     * @param  array<string,mixed>  $qualityGate
     * @param  array<string,mixed>|null  $context
     * @param  array<string,mixed>  $provenance
     */
    public function __construct(
        public string $findingId,
        public string $projectId,
        public string $ruleId,
        public AutomationLevel $automationLevel,
        public bool $guidanceAvailable,
        public array $guidance,
        public array $finding,
        public ?array $dependency,
        public array $evidence,
        public array $validation,
        public array $references,
        public array $warnings,
        public array $lifecycle,
        public array $source,
        public array $qualityGate,
        public ?array $context,
        public array $provenance,
        public FindingStatus $status,
    ) {}

    /**
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        return [
            'finding_id' => $this->findingId,
            'project_id' => $this->projectId,
            'rule_id' => $this->ruleId,
            'automation_level' => $this->automationLevel->value,
            'guidance_available' => $this->guidanceAvailable,
            'lifecycle' => $this->lifecycle,
            'guidance' => $this->guidance,
            'validation' => $this->validation,
            'references' => array_map(fn (string $url): array => ['url' => $url], $this->references),
            'warnings' => $this->warnings,
            'source' => $this->source,
            'quality_gate' => $this->qualityGate,
            'context' => $this->context,
            'dependency' => $this->dependency,
            'finding' => $this->finding,
            'evidence' => $this->evidence,
            'provenance' => $this->provenance,
        ];
    }
}
